[2022-07-27 15:02:59,818] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.inaccurate manual__2022-07-27T14:58:04.465454+00:00 [queued]>
[2022-07-27 15:02:59,844] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.inaccurate manual__2022-07-27T14:58:04.465454+00:00 [queued]>
[2022-07-27 15:02:59,845] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 15:02:59,845] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-27 15:02:59,845] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 15:02:59,873] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-27 14:58:04.465454+00:00
[2022-07-27 15:02:59,883] {standard_task_runner.py:52} INFO - Started process 1425 to run task
[2022-07-27 15:02:59,889] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag', 'inaccurate', 'manual__2022-07-27T14:58:04.465454+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6taz59o6', '--error-file', '/tmp/tmprk7u1b1i']
[2022-07-27 15:02:59,890] {standard_task_runner.py:80} INFO - Job 46: Subtask inaccurate
[2022-07-27 15:03:00,016] {task_command.py:371} INFO - Running <TaskInstance: dag.inaccurate manual__2022-07-27T14:58:04.465454+00:00 [running]> on host c054a673cb8f
[2022-07-27 15:03:00,173] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-27T14:58:04.465454+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-27T14:58:04.465454+00:00
[2022-07-27 15:03:00,175] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-27 15:03:00,177] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-07-27 15:03:00,200] {subprocess.py:85} INFO - Output:
[2022-07-27 15:03:00,204] {subprocess.py:92} INFO - inaccurate
[2022-07-27 15:03:00,204] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-27 15:03:00,277] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag, task_id=inaccurate, execution_date=20220727T145804, start_date=20220727T150259, end_date=20220727T150300
[2022-07-27 15:03:00,341] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-27 15:03:00,412] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
