[2022-07-27 14:46:43,673] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.choose_best_model manual__2022-07-27T14:46:37.154525+00:00 [queued]>
[2022-07-27 14:46:43,710] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.choose_best_model manual__2022-07-27T14:46:37.154525+00:00 [queued]>
[2022-07-27 14:46:43,710] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 14:46:43,710] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-27 14:46:43,710] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 14:46:43,747] {taskinstance.py:1397} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-07-27 14:46:37.154525+00:00
[2022-07-27 14:46:43,758] {standard_task_runner.py:52} INFO - Started process 685 to run task
[2022-07-27 14:46:43,771] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag', 'choose_best_model', 'manual__2022-07-27T14:46:37.154525+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpy5ack7tp', '--error-file', '/tmp/tmp82djdezg']
[2022-07-27 14:46:43,772] {standard_task_runner.py:80} INFO - Job 14: Subtask choose_best_model
[2022-07-27 14:46:44,004] {task_command.py:371} INFO - Running <TaskInstance: dag.choose_best_model manual__2022-07-27T14:46:37.154525+00:00 [running]> on host c054a673cb8f
[2022-07-27 14:46:44,445] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-07-27T14:46:37.154525+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-27T14:46:37.154525+00:00
[2022-07-27 14:46:44,456] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: _choose_best_model() missing 1 required positional argument: 'task_id'
[2022-07-27 14:46:44,503] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag, task_id=choose_best_model, execution_date=20220727T144637, start_date=20220727T144643, end_date=20220727T144644
[2022-07-27 14:46:44,621] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task choose_best_model (_choose_best_model() missing 1 required positional argument: 'task_id'; 685)
[2022-07-27 14:46:44,648] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-27 14:46:44,870] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
