[2022-07-27 15:08:56,384] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.inaccurate scheduled__2022-07-26T00:00:00+00:00 [queued]>
[2022-07-27 15:08:56,419] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.inaccurate scheduled__2022-07-26T00:00:00+00:00 [queued]>
[2022-07-27 15:08:56,419] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 15:08:56,420] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-27 15:08:56,420] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 15:08:56,460] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-26 00:00:00+00:00
[2022-07-27 15:08:56,471] {standard_task_runner.py:52} INFO - Started process 1728 to run task
[2022-07-27 15:08:56,486] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag', 'inaccurate', 'scheduled__2022-07-26T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp4j8mbhud', '--error-file', '/tmp/tmpw2uc40ws']
[2022-07-27 15:08:56,486] {standard_task_runner.py:80} INFO - Job 70: Subtask inaccurate
[2022-07-27 15:08:56,644] {task_command.py:371} INFO - Running <TaskInstance: dag.inaccurate scheduled__2022-07-26T00:00:00+00:00 [running]> on host c054a673cb8f
[2022-07-27 15:08:56,850] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-26T00:00:00+00:00
[2022-07-27 15:08:56,852] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-27 15:08:56,853] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-07-27 15:08:56,877] {subprocess.py:85} INFO - Output:
[2022-07-27 15:08:56,881] {subprocess.py:92} INFO - inaccurate
[2022-07-27 15:08:56,882] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-27 15:08:56,955] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag, task_id=inaccurate, execution_date=20220726T000000, start_date=20220727T150856, end_date=20220727T150856
[2022-07-27 15:08:57,025] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-27 15:08:57,102] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
