[2022-07-27 14:59:26,565] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.choose_best_model manual__2022-07-27T14:58:04.465454+00:00 [queued]>
[2022-07-27 14:59:26,589] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.choose_best_model manual__2022-07-27T14:58:04.465454+00:00 [queued]>
[2022-07-27 14:59:26,589] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 14:59:26,589] {taskinstance.py:1377} INFO - Starting attempt 3 of 3
[2022-07-27 14:59:26,589] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 14:59:26,620] {taskinstance.py:1397} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-07-27 14:58:04.465454+00:00
[2022-07-27 14:59:26,630] {standard_task_runner.py:52} INFO - Started process 1247 to run task
[2022-07-27 14:59:26,636] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag', 'choose_best_model', 'manual__2022-07-27T14:58:04.465454+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxjwayy84', '--error-file', '/tmp/tmp_hani3hq']
[2022-07-27 14:59:26,637] {standard_task_runner.py:80} INFO - Job 31: Subtask choose_best_model
[2022-07-27 14:59:26,766] {task_command.py:371} INFO - Running <TaskInstance: dag.choose_best_model manual__2022-07-27T14:58:04.465454+00:00 [running]> on host c054a673cb8f
[2022-07-27 14:59:26,932] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-07-27T14:58:04.465454+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-27T14:58:04.465454+00:00
[2022-07-27 14:59:26,934] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: _choose_best_model() missing 1 required positional argument: 't_id'
[2022-07-27 14:59:26,953] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag, task_id=choose_best_model, execution_date=20220727T145804, start_date=20220727T145926, end_date=20220727T145926
[2022-07-27 14:59:26,978] {standard_task_runner.py:97} ERROR - Failed to execute job 31 for task choose_best_model (_choose_best_model() missing 1 required positional argument: 't_id'; 1247)
[2022-07-27 14:59:27,047] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-27 14:59:27,206] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
